# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReusebleUIKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReusebleUIKitExample

  pod 'ReusebleUIKit', :path => '../../'
  
  #UI
  
  pod 'SnapKit', '~> 5.0.0'
  
  pod 'CoreCollections',
    :git => 'https://github.com/skibinalexander/CoreCollections.git/',
    :tag => '0.6.1'

end
